[General]
Version=1
Title=Modo Aluno
Subtitle=Escolha uma atividade
HomeCount=6
GameCount=5
GamesEnabled=1

[Security]
; SENHAS DE TESTE - troque depois
ExitPassword=1234
RestrictedPassword=4321

[Special]
Enabled=0
Name=FAZER PROVA
Type=web
Target=https://example.com/prova
Protected=0

[Home1]
Name=Google
Type=web
Target=https://www.google.com
Protected=0

[Home2]
Name=Tux Paint
Type=exe
Target=C:\Program Files\TuxPaint\tuxpaint.exe
Protected=0

[Home3]
Name=Poki
Type=web
Target=https://poki.com/
Protected=0

[Home4]
Name=TypingLand
Type=exe
Target=C:\Program Files\TypingLand\TypingLand.exe
Protected=0

[Home5]
Name=PowerPoint
Type=command
Target=powerpnt.exe
Protected=0

[Home6]
Name=Canva
Type=web
Target=https://www.canva.com/
Protected=0

[Game1]
Name=Geometry Dash
Type=exe
Target=C:\Jogos\GeometryDash\GeometryDash.exe
Protected=0

[Game2]
Name=diep.io
Type=web
Target=https://diep.io/
Protected=0

[Game3]
Name=Muito, Muito Minimalista
Type=exe
Target=C:\Jogos\MMM\MMM.exe
Protected=0

[Game4]
Name=FNAF Web
Type=web
Target=https://example.com/fnaf-web
Protected=1

[Game5]
Name=Futbobo
Type=web
Target=https://futbobo.top
Protected=0
